### ISSUE TITLE
Linkvetise not working!

### ISSUE THREAD

**Issue by Sharesystems** [Heliactyl/Heliactyl-11#24]
Hi there,
I downloaded the latest version (where LV should already be fixed). Unfortunately, this version doesn't work either.

When you click Generate Link, the website takes an extremely long time to load and won't stop. Did I make a mistake or is this still a bug?

There is also an error in the console:
```
(node:26) UnhandledPromiseRejectionWarning: ReferenceError: makeid is not defined
    at eval (eval at <anonymous> (/home/container/api/lv2.js:7:1), <anonymous>:1:1142)
    at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/container/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/container/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5)
    at /home/container/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/container/node_modules/express/lib/router/index.js:341:12)
    at next (/home/container/node_modules/express/lib/router/index.js:275:10)
    at /home/container/index.js:174:3
    at Layer.handle [as handle_request] (/home/container/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by saiswar5516T** [comment]
You may have forgot to edit settings.json

**Comment by pl3xed** [comment]
You forgot to configure it in settings.json
I'll add a toggle to enable/disable it in v11.3.1

**Comment by Sharesystems** [comment]
Maybe I got the userid wrong. But where can I find them?
Is this her?
```
<script src="https://publisher.linkvertise.com/cdn/linkvertise.js"></script><script>linkvertise(USERID, {whitelist: [], blacklist: []});</script>
```
If not where can I find them?
If so, then LV does not work.

**Comment by SamCoThePug** [comment]
Update your Heliactyl and itll be fixed.

**Comment by SamCoThePug** [comment]
> Maybe I got the userid wrong. But where can I find them? Is this her?
> 
> ```
> <script src="https://publisher.linkvertise.com/cdn/linkvertise.js"></script><script>linkvertise(USERID, {whitelist: [], blacklist: []});</script>
> ```
> 
> If not where can I find them? If so, then LV does not work.

Thats how you get userID, update heliactyl, i fixed linkvertise a few minutes ago.
